import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import { connectDB } from "./utils/db.js";
import salesRoutes from "./routes/salesRoutes.js";
dotenv.config();
connectDB();
const app = express();
app.use(cors());
app.use(express.json());
app.use("/api/sales", salesRoutes);
app.listen(process.env.PORT || 5000, () => console.log("Backend running"));